# Generated by Django 4.2.1 on 2023-05-14 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('email', models.TextField(max_length=255)),
                ('senha', models.TextField(max_length=128)),
                ('token', models.TextField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Voluntarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('telefone', models.TextField(max_length=24)),
                ('email', models.TextField(max_length=255)),
                ('observacoes', models.TextField(max_length=600)),
            ],
        ),
    ]
