# Generated by Django 4.2.1 on 2023-05-14 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_baus', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admins',
            new_name='Admin',
        ),
        migrations.RenameModel(
            old_name='Voluntarios',
            new_name='Voluntario',
        ),
    ]
