# Generated by Django 4.2.1 on 2023-05-14 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_baus', '0002_rename_admins_admin_rename_voluntarios_voluntario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='Admins',
        ),
        migrations.RenameModel(
            old_name='Voluntario',
            new_name='Voluntarios',
        ),
    ]
