# Generated by Django 4.2.1 on 2023-05-14 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_baus', '0003_rename_admin_admins_rename_voluntario_voluntarios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voluntarios',
            old_name='observacoes',
            new_name='mensagem',
        ),
    ]
