# Generated by Django 4.2.1 on 2023-05-14 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_baus', '0005_voluntarios_data_cadastro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voluntarios',
            name='data_cadastro',
        ),
    ]
